spring.application.name=yabab

# ??
server.port=18090

# DB ??
spring.datasource.url=jdbc:oracle:thin:@116.36.205.25:1522:XE
spring.datasource.username=c##final
spring.datasource.password=final
spring.datasource.drvier-class-name=oracle.jdbc.OracleDriver

# mybatis ??
mybatis.type-aliases-package=fs.human.yabab.*.vo
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# JSON ?? ?? ?? ??
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
